# Generated by Django 4.2.1 on 2023-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_consultations_heure_de_consultation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="dimanche",
            field=models.CharField(default="Bientot", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="jeudi",
            field=models.CharField(default="8H - 12H", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lundi",
            field=models.CharField(default="9H - 11H", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="mardi",
            field=models.CharField(default="13H - 15H", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="mercredi",
            field=models.CharField(default="10H - 14H", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="samedi",
            field=models.CharField(default="9H - 12H", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="vendredi",
            field=models.CharField(default="14H - 18H", max_length=50),
        ),
    ]
