# Generated by Django 4.2.1 on 2023-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_consultations_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="dimanche",
            field=models.CharField(default="9h - 15h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="jeudi",
            field=models.CharField(default="8h - 12h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lundi",
            field=models.CharField(default="9h - 11h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="mardi",
            field=models.CharField(default="13h - 15h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="mercredi",
            field=models.CharField(default="10h - 14h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="samedi",
            field=models.CharField(default="9h - 12h", max_length=50),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="vendredi",
            field=models.CharField(default="14h - 18h", max_length=50),
        ),
    ]
